openapi: 3.0.0
info:
  title: North Carolina Building Code
  description: API documentation for the North Carolina Building Code, including general and special requirements.
  version: 1.0.0
servers:
  - url: https://www.ncosfm.gov/codes
paths:
  /building-requirements:
    get:
      summary: Get Building Requirements
      description: Retrieve the general requirements for the North Carolina Building Code.
      responses:
        '200':
          description: A list of building requirements
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /special-requirements:
    get:
      summary: Get Special Requirements
      description: Retrieve the special requirements for the North Carolina Building Code.
      responses:
        '200':
          description: A list of special requirements
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /permits:
    get:
      summary: Get Permit Requirements
      description: Retrieve information about building permit requirements in North Carolina.
      responses:
        '200':
          description: Information about permit requirements
          content:
            application/json:
              schema:
                type: object
                properties:
                  requirements:
                    type: array
                    items:
                      type: string
                  exemptions:
                    type: array
                    items:
                      type: string
                  applicationProcess:
                    type: string

  /inspections:
    get:
      summary: Get Inspection Information
      description: Retrieve information about required building inspections in North Carolina.
      responses:
        '200':
          description: Information about inspections
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      example: "Foundation Inspection"
                    description:
                      type: string
                      example: "Inspection of foundation elements before concealment"
                    timing:
                      type: string
                      example: "After foundation is complete but before backfill"
components:
  schemas:
    BuildingRequirement:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
    SpecialRequirement:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string